### ISSUE TITLE
Compile guide / usage guide

### ISSUE THREAD

**Issue by danrobi11** [tofudd/lanchat#8]
The project could use a compile guide/dependencies and usage guide /connect [IP], /send [short ID] [file path] , /exit, short ID= etc

**Comment by tofudd** [comment]
Usage guide shows during first launch (or if you don't have config file).
I didn't add compile guide because it's same as other dotnet projects.

1. Clone repo.
2. Get into project directory. For example `lanchat/Lanchat.Terminal`
3. `dotnet build`

[https://docs.microsoft.com/pl-pl/dotnet/core/tools/dotnet-build](https://docs.microsoft.com/pl-pl/dotnet/core/tools/dotnet-build)

**Comment by danrobi11** [comment]
> Usage guide shows during first launch (or if you don't have config file)

Ya theres no config file with linux binary because I've never seen the usage guide during first launch.

Im guessing you mean ```.Lancaht2/config.json```

Thats what in it:

```
{
  "BlockedAddresses": [],
  "Port": 3645,
  "BroadcastPort": 3646,
  "Nickname": "Byakuren",
  "AutomaticConnecting": true,
  "UseIPv6": false,
  "Language": null
}
```

**Comment by tofudd** [comment]
Yup. Guide was added in 2.6. If you have used the previous version the config has already been generated and the guide will not appear.
